---
# Deploy the haproxy server
#
- name: Install python2-httpie
  package:
    name: python2-httpie
    state: latest 

- name: Install HAProxy
  package:
    name: haproxy
    state: latest

- name: Setup HAProxy config files
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: Restart haproxy

- name: Enable HAProxy to start at boot
  service:
    name: haproxy
    enabled: yes
