---
# Install and setup apache
#
- name: Install apache package
  package:
    name: httpd
    state: latest
  tags:
   - install

- name: Enable and start apache
  service:
    name: httpd
    enabled: yes
    state: started
  tags:
    - services
